# Generated by Django 4.1.6 on 2023-02-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('linkedin', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('graduation_date', models.DateField()),
                ('majors', models.CharField(max_length=255)),
                ('sphere', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('current_company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('previous_companies', models.TextField(blank=True)),
            ],
        ),
    ]
